name: Build
permissions: 
  contents: read
  deployments: write
  id-token: write

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup.yml

      - name: Build
        run: npm run build

      - name: Run type checking
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: CI
      url: ${{ steps.deploy-url.outputs.site_url }}
    env:
      SST_PRINT_LOGS: 1
      SST_STAGE: PR-${{ github.event.number }}
    needs:
      - validate
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup.yml

      - name: Set Secrets
        run: |
          npm run sst -- secret set JwtSecret ${{ secrets.JWT_SECRET }}

      - name: Deploy app
        run: npm run deploy
        env:
          ALLOW_DUPLICATE_PROJECT_IDENTITIES: ${{ secrets.ALLOW_DUPLICATE_PROJECT_IDENTITIES }}
          APP_URL: ${{ secrets.APP_URL }}
          DEFAULT_EMAIL: ${{ secrets.DEFAULT_EMAIL }}
          DISABLE_SIGNUPS: ${{ secrets.DISABLE_SIGNUPS }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          METRICS_ENABLED: true

      - name: Get Deploy URL
        id: deploy-url
        run: |
          cat .sst/outputs.json | jq -r '.site'
          echo SITE_URL=$SITE_URL >> $GITHUB_ENV

  post-deploy:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup.yml

      - name: Install Playwright Browsers
        working-directory: packages/dashboard

        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: packages/dashboard
        run: npm run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./packages/dashboard/playwright-report/
          retention-days: 7